In [1]:
import pandas as pd
from sklearn.utils import shuffle
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.cross_validation import cross_val_score
from sklearn.ensemble import RandomForestClassifier
import pickle

/home/eoin/anaconda3/envs/Software/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [2]:
import bikefind

In [3]:
from bikefind.linearRegression import getHistoricalTable

In [4]:
df_merge = getHistoricalTable()

In [5]:
df_merge.head(10)

,time_x,address,totalBikeStands,availableBikeStands,availableBikes,status,datetime_x,date,day,hour,...,currentTemp,maxTemp,minTemp,pressure,humidity,windSpeed,windAngle,cloudDensity,visibility,datetime_y
0,1521225890000,Newman House,40,37,3,OPEN,2018-03-16 18:44:50,2018-03-16,Friday,18,...,279.71,280.15,279.15,1000,93,6.7,110,40,10000,2018-03-16 18:30:00
1,1521225890000,Western Way,40,39,1,CLOSED,2018-03-16 18:44:50,2018-03-16,Friday,18,...,279.71,280.15,279.15,1000,93,6.7,110,40,10000,2018-03-16 18:30:00
2,1521225891000,York Street West,40,33,7,OPEN,2018-03-16 18:44:51,2018-03-16,Friday,18,...,279.71,280.15,279.15,1000,93,6.7,110,40,10000,2018-03-16 18:30:00
3,1521225909000,Mount Brown,22,12,10,OPEN,2018-03-16 18:45:09,2018-03-16,Friday,18,...,279.71,280.15,279.15,1000,93,6.7,110,40,10000,2018-03-16 18:30:00
4,1521225951000,Brookfield Road,30,12,18,OPEN,2018-03-16 18:45:51,2018-03-16,Friday,18,...,279.71,280.15,279.15,1000,93,6.7,110,40,10000,2018-03-16 18:30:00
5,1521225972000,Eccles Street East,27,26,1,OPEN,2018-03-16 18:46:12,2018-03-16,Friday,18,...,279.71,280.15,279.15,1000,93,6.7,110,40,10000,2018-03-16 18:30:00
6,1521225982000,Fitzwilliam Square East,40,0,0,CLOSED,2018-03-16 18:46:22,2018-03-16,Friday,18,...,279.71,280.15,279.15,1000,93,6.7,110,40,10000,2018-03-16 18:30:00
7,1521225985000,Collins Barracks Museum,38,19,19,OPEN,2018-03-16 18:46:25,2018-03-16,Friday,18,...,279.71,280.15,279.15,1000,93,6.7,110,40,10000,2018-03-16 18:30:00
8,1521225995000,Merrion Square West,20,20,0,CLOSED,2018-03-16 18:46:35,2018-03-16,Friday,18,...,279.71,280.15,279.15,1000,93,6.7,110,40,10000,2018-03-16 18:30:00
9,1521226003000,Benson Street,40,0,0,CLOSED,2018-03-16 18:46:43,2018-03-16,Friday,18,...,279.71,280.15,279.15,1000,93,6.7,110,40,10000,2018-03-16 18:30:00

In [6]:
df_merge.dtypes

time_x                          int64
address                        object
totalBikeStands                 int64
availableBikeStands             int64
availableBikes                  int64
status                         object
datetime_x             datetime64[ns]
date                           object
day                            object
hour                            int64
time_y                          int64
mainDescription                object
detailedDescription            object
icon                           object
currentTemp                   float64
maxTemp                       float64
minTemp                       float64
pressure                        int64
humidity                        int64
windSpeed                     float64
windAngle                       int64
cloudDensity                    int64
visibility                      int64
datetime_y             datetime64[ns]
dtype: object

In [7]:
df_merge['hour'] = df_merge['hour'].astype('category')
df_merge.dtypes

time_x                          int64
address                        object
totalBikeStands                 int64
availableBikeStands             int64
availableBikes                  int64
status                         object
datetime_x             datetime64[ns]
date                           object
day                            object
hour                         category
time_y                          int64
mainDescription                object
detailedDescription            object
icon                           object
currentTemp                   float64
maxTemp                       float64
minTemp                       float64
pressure                        int64
humidity                        int64
windSpeed                     float64
windAngle                       int64
cloudDensity                    int64
visibility                      int64
datetime_y             datetime64[ns]
dtype: object

In [8]:
for column in ['time_x', 'datetime_x', 'time_y', 'datetime_y', 'visibility', 'icon']:
    del df_merge[column]
df_merge.head(10)

,address,totalBikeStands,availableBikeStands,availableBikes,status,date,day,hour,mainDescription,detailedDescription,currentTemp,maxTemp,minTemp,pressure,humidity,windSpeed,windAngle,cloudDensity
0,Newman House,40,37,3,OPEN,2018-03-16,Friday,18,Clouds,scattered clouds,279.71,280.15,279.15,1000,93,6.7,110,40
1,Western Way,40,39,1,CLOSED,2018-03-16,Friday,18,Clouds,scattered clouds,279.71,280.15,279.15,1000,93,6.7,110,40
2,York Street West,40,33,7,OPEN,2018-03-16,Friday,18,Clouds,scattered clouds,279.71,280.15,279.15,1000,93,6.7,110,40
3,Mount Brown,22,12,10,OPEN,2018-03-16,Friday,18,Clouds,scattered clouds,279.71,280.15,279.15,1000,93,6.7,110,40
4,Brookfield Road,30,12,18,OPEN,2018-03-16,Friday,18,Clouds,scattered clouds,279.71,280.15,279.15,1000,93,6.7,110,40
5,Eccles Street East,27,26,1,OPEN,2018-03-16,Friday,18,Clouds,scattered clouds,279.71,280.15,279.15,1000,93,6.7,110,40
6,Fitzwilliam Square East,40,0,0,CLOSED,2018-03-16,Friday,18,Clouds,scattered clouds,279.71,280.15,279.15,1000,93,6.7,110,40
7,Collins Barracks Museum,38,19,19,OPEN,2018-03-16,Friday,18,Clouds,scattered clouds,279.71,280.15,279.15,1000,93,6.7,110,40
8,Merrion Square West,20,20,0,CLOSED,2018-03-16,Friday,18,Clouds,scattered clouds,279.71,280.15,279.15,1000,93,6.7,110,40
9,Benson Street,40,0,0,CLOSED,2018-03-16,Friday,18,Clouds,scattered clouds,279.71,280.15,279.15,1000,93,6.7,110,40

In [9]:
df_merge.shape

(865752, 18)

In [10]:
df_merge.sort_values(by='date')

,address,totalBikeStands,availableBikeStands,availableBikes,status,date,day,hour,mainDescription,detailedDescription,currentTemp,maxTemp,minTemp,pressure,humidity,windSpeed,windAngle,cloudDensity
0,Newman House,40,37,3,OPEN,2018-03-16,Friday,18,Clouds,scattered clouds,279.71,280.15,279.15,1000,93,6.7,110,40
4962,Jervis Street,21,19,2,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1004,87,6.7,80,75
4961,Jervis Street,21,19,2,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1003,87,7.2,80,75
4960,Portobello Harbour,30,8,22,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1004,87,6.7,80,75
4959,Portobello Harbour,30,8,22,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1003,87,7.2,80,75
4958,Parnell Street,20,12,8,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1004,87,6.7,80,75
4957,Parnell Street,20,12,8,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1003,87,7.2,80,75
4956,Grand Canal Dock,40,40,0,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1004,87,6.7,80,75
4955,Grand Canal Dock,40,40,0,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1003,87,7.2,80,75
4954,Princes Street / O'Connell Street,23,0,23,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1004,87,6.7,80,75
4953,Princes Street / O'Connell Street,23,0,23,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1003,87,7.2,80,75
4952,Portobello Road,30,6,24,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1004,87,6.7,80,75
4951,Portobello Road,30,6,24,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1003,87,7.2,80,75
4950,York Street West,40,29,11,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1004,87,6.7,80,75
4949,York Street West,40,29,11,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1003,87,7.2,80,75
4948,The Point,40,9,31,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1004,87,6.7,80,75
4947,The Point,40,9,31,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1003,87,7.2,80,75
4946,Cathal Brugha Street,20,6,14,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1004,87,6.7,80,75
4945,Cathal Brugha Street,20,6,14,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1003,87,7.2,80,75
4944,Christchurch Place,20,0,0,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1004,87,6.7,80,75
4943,Christchurch Place,20,0,0,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1003,87,7.2,80,75
4942,Blessington Street,20,8,12,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1004,87,6.7,80,75
4941,Blessington Street,20,8,12,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1003,87,7.2,80,75
4940,Leinster Street South,30,9,21,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1004,87,6.7,80,75
4939,Leinster Street South,30,9,21,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1003,87,7.2,80,75
4938,Merrion Square West,20,20,0,CLOSED,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1004,87,6.7,80,75
4963,Bolton Street,20,17,3,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1003,87,7.2,80,75
4937,Merrion Square West,20,20,0,CLOSED,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1003,87,7.2,80,75
4964,Bolton Street,20,17,3,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1004,87,6.7,80,75
4966,Fitzwilliam Square West,30,28,2,OPEN,2018-03-16,Friday,22,Clouds,broken clouds,280.15,280.15,280.15,1004,87,6.7,80,75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
841392,Eccles Street East,27,24,3,OPEN,2018-04-16,Monday,7,Clouds,few clouds,281.15,281.15,281.15,1004,75,5.1,190,20
841393,Eccles Street East,27,24,3,OPEN,2018-04-16,Monday,7,Clouds,few clouds,282.15,282.15,282.15,1005,70,4.6,190,20
841387,Denmark Street Great,20,9,11,OPEN,2018-04-16,Monday,7,Clouds,few clouds,282.15,282.15,282.15,1005,70,4.6,190,20
841394,Jervis Street,21,15,6,OPEN,2018-04-16,Monday,7,Clouds,few clouds,281.15,281.15,281.15,1004,75,5.1,190,20
841396,Hardwicke Place,25,22,3,OPEN,2018-04-16,Monday,7,Clouds,few clouds,281.15,281.15,281.15,1004,75,5.1,190,20
841397,Hardwicke Place,25,22,3,OPEN,2018-04-16,Monday,7,Clouds,few clouds,282.15,282.15,282.15,1005,70,4.6,190,20
841398,Parnell Street,20,18,2,OPEN,2018-04-16,Monday,7,Clouds,few clouds,281.15,281.15,281.15,1004,75,5.1,190,20
841399,Parnell Street,20,18,2,OPEN,2018-04-16,Monday,7,Clouds,few clouds,282.15,282.15,282.15,1005,70,4.6,190,20
841400,Mount Street Lower,40,0,39,OPEN,2018-04-16,Monday,7,Clouds,few clouds,281.15,281.15,281.15,1004,75,5.1,190,20
841401,Mount Street Lower,40,0,39,OPEN,2018-04-16,Monday,7,Clouds,few clouds,282.15,282.15,282.15,1005,70,4.6,190,20
841395,Jervis Street,21,15,6,OPEN,2018-04-16,Monday,7,Clouds,few clouds,282.15,282.15,282.15,1005,70,4.6,190,20
841368,Mount Brown,22,22,0,OPEN,2018-04-16,Monday,7,Clouds,few clouds,281.15,281.15,281.15,1004,75,5.1,190,20
841386,Denmark Street Great,20,9,11,OPEN,2018-04-16,Monday,7,Clouds,few clouds,281.15,281.15,281.15,1004,75,5.1,190,20
841384,Cathal Brugha Street,20,16,4,OPEN,2018-04-16,Monday,7,Clouds,few clouds,281.15,281.15,281.15,1004,75,5.1,190,20
841370,Blackhall Place,30,30,0,OPEN,2018-04-16,Monday,7,Clouds,few clouds,281.15,281.15,281.15,1004,75,5.1,190,20
841371,Blackhall Place,30,30,0,OPEN,2018-04-16,Monday,7,Clouds,few clouds,282.15,282.15,282.15,1005,70,4.6,190,20
841372,Blessington Street,20,20,0,OPEN,2018-04-16,Monday,7,Clouds,few clouds,281.15,281.15,281.15,1004,75,5.1,190,20
841373,Blessington Street,20,20,0,OPEN,2018-04-16,Monday,7,Clouds,few clouds,282.15,282.15,282.15,1005,70,4.6,190,20
841374,Grangegorman Lower (Central),40,29,11,OPEN,2018-04-16,Monday,7,Clouds,few clouds,281.15,281.15,281.15,1004,75,5.1,190,20
841375,Grangegorman Lower (Central),40,29,11,OPEN,2018-04-16,Monday,7,Clouds,few clouds,282.15,282.15,282.15,1005,70,4.6,190,20
841385,Cathal Brugha Street,20,16,4,OPEN,2018-04-16,Monday,7,Clouds,few clouds,282.15,282.15,282.15,1005,70,4.6,190,20
841376,Earlsfort Terrace,30,0,30,OPEN,2018-04-16,Monday,7,Clouds,few clouds,281.15,281.15,281.15,1004,75,5.1,190,20
841378,Parkgate Street,38,38,0,OPEN,2018-04-16,Monday,7,Clouds,few clouds,281.15,281.15,281.15,1004,75,5.1,190,20
841379,Parkgate Street,38,38,0,OPEN,2018-04-16,Monday,7,Clouds,few clouds,282.15,282.15,282.15,1005,70,4.6,190,20
841380,Sandwith Street,40,30,10,OPEN,2018-04-16,Monday,7,Clouds,few clouds,281.15,281.15,281.15,1004,75,5.1,190,20
841381,Sandwith Street,40,30,10,OPEN,2018-04-16,Monday,7,Clouds,few clouds,282.15,282.15,282.15,1005,70,4.6,190,20
841382,Grangegorman Lower (North),36,36,0,OPEN,2018-04-16,Monday,7,Clouds,few clouds,281.15,281.15,281.15,1004,75,5.1,190,20
841383,Grangegorman Lower (North),36,36,0,OPEN,2018-04-16,Monday,7,Clouds,few clouds,282.15,282.15,282.15,1005,70,4.6,190,20
841377,Earlsfort Terrace,30,0,30,OPEN,2018-04-16,Monday,7,Clouds,few clouds,282.15,282.15,282.15,1005,70,4.6,190,20
865751,Custom House,30,2,28,OPEN,2018-04-16,Monday,20,Rain,light rain,283.15,283.15,283.15,1002,87,12.9,170,75

In [11]:
df_merge.groupby('mainDescription').count().sort_values(by='address', ascending=False)

,address,totalBikeStands,availableBikeStands,availableBikes,status,date,day,hour,detailedDescription,currentTemp,maxTemp,minTemp,pressure,humidity,windSpeed,windAngle,cloudDensity
mainDescription,,,,,,,,,,,,,,,,,
Clouds,457941,457941,457941,457941,457941,457941,457941,457941,457941,457941,457941,457941,457941,457941,457941,457941,457941
Rain,181364,181364,181364,181364,181364,181364,181364,181364,181364,181364,181364,181364,181364,181364,181364,181364,181364
Drizzle,109733,109733,109733,109733,109733,109733,109733,109733,109733,109733,109733,109733,109733,109733,109733,109733,109733
Mist,40757,40757,40757,40757,40757,40757,40757,40757,40757,40757,40757,40757,40757,40757,40757,40757,40757
Snow,30704,30704,30704,30704,30704,30704,30704,30704,30704,30704,30704,30704,30704,30704,30704,30704,30704
Clear,23913,23913,23913,23913,23913,23913,23913,23913,23913,23913,23913,23913,23913,23913,23913,23913,23913
Fog,21340,21340,21340,21340,21340,21340,21340,21340,21340,21340,21340,21340,21340,21340,21340,21340,21340

In [12]:
print("All the weather that has happened in the last four weeks")
df_merge.groupby('detailedDescription').count().sort_values(by='address', ascending=False)

All the weather that has happened in the last four weeks

,address,totalBikeStands,availableBikeStands,availableBikes,status,date,day,hour,mainDescription,currentTemp,maxTemp,minTemp,pressure,humidity,windSpeed,windAngle,cloudDensity
detailedDescription,,,,,,,,,,,,,,,,,
broken clouds,330058,330058,330058,330058,330058,330058,330058,330058,330058,330058,330058,330058,330058,330058,330058,330058,330058
light rain,103028,103028,103028,103028,103028,103028,103028,103028,103028,103028,103028,103028,103028,103028,103028,103028,103028
scattered clouds,83423,83423,83423,83423,83423,83423,83423,83423,83423,83423,83423,83423,83423,83423,83423,83423,83423
light intensity drizzle,74816,74816,74816,74816,74816,74816,74816,74816,74816,74816,74816,74816,74816,74816,74816,74816,74816
shower rain,44053,44053,44053,44053,44053,44053,44053,44053,44053,44053,44053,44053,44053,44053,44053,44053,44053
few clouds,43379,43379,43379,43379,43379,43379,43379,43379,43379,43379,43379,43379,43379,43379,43379,43379,43379
mist,40757,40757,40757,40757,40757,40757,40757,40757,40757,40757,40757,40757,40757,40757,40757,40757,40757
light intensity drizzle rain,34917,34917,34917,34917,34917,34917,34917,34917,34917,34917,34917,34917,34917,34917,34917,34917,34917
light intensity shower rain,26480,26480,26480,26480,26480,26480,26480,26480,26480,26480,26480,26480,26480,26480,26480,26480,26480
clear sky,23913,23913,23913,23913,23913,23913,23913,23913,23913,23913,23913,23913,23913,23913,23913,23913,23913
fog,21340,21340,21340,21340,21340,21340,21340,21340,21340,21340,21340,21340,21340,21340,21340,21340,21340
light shower snow,20384,20384,20384,20384,20384,20384,20384,20384,20384,20384,20384,20384,20384,20384,20384,20384,20384
moderate rain,7803,7803,7803,7803,7803,7803,7803,7803,7803,7803,7803,7803,7803,7803,7803,7803,7803
light snow,4326,4326,4326,4326,4326,4326,4326,4326,4326,4326,4326,4326,4326,4326,4326,4326,4326
shower sleet,3534,3534,3534,3534,3534,3534,3534,3534,3534,3534,3534,3534,3534,3534,3534,3534,3534
shower snow,2460,2460,2460,2460,2460,2460,2460,2460,2460,2460,2460,2460,2460,2460,2460,2460,2460
overcast clouds,1081,1081,1081,1081,1081,1081,1081,1081,1081,1081,1081,1081,1081,1081,1081,1081,1081

In [13]:
target = 'availableBikes'
descriptive = [ 'day', 'hour', 'address', 'mainDescription', 'detailedDescription', 'currentTemp', 'pressure', 'humidity', 'windSpeed', 'windAngle', 'cloudDensity', 'Intercept']

In [14]:
df_merge = shuffle(df_merge)

In [15]:
df_merge.head(10)

,address,totalBikeStands,availableBikeStands,availableBikes,status,date,day,hour,mainDescription,detailedDescription,currentTemp,maxTemp,minTemp,pressure,humidity,windSpeed,windAngle,cloudDensity
359086,Blackhall Place,30,30,0,OPEN,2018-03-28,Wednesday,9,Clouds,broken clouds,277.15,277.15,277.15,1004,86,7.2,270,75
282903,Clonmel Street,33,0,33,OPEN,2018-03-26,Monday,8,Clear,clear sky,279.13,279.13,279.13,1026,100,1.6,237,0
799598,Eccles Street East,27,27,0,OPEN,2018-04-15,Sunday,3,Mist,mist,281.73,282.15,281.15,1006,100,6.7,140,75
255543,Talbot Street,40,3,37,OPEN,2018-03-25,Sunday,13,Clouds,scattered clouds,282.64,283.15,282.15,1014,57,5.1,290,40
402842,Grattan Street,23,20,3,OPEN,2018-03-30,Friday,15,Clouds,broken clouds,279.15,279.15,279.15,998,87,7.2,20,75
320374,Golden Lane,20,19,1,OPEN,2018-03-27,Tuesday,8,Drizzle,light intensity drizzle,280.64,281.15,280.15,1003,81,8.7,280,40
864049,Brookfield Road,30,8,22,OPEN,2018-04-16,Monday,19,Rain,light rain,283.72,284.15,283.15,1003,87,11.8,170,75
232230,Grantham Street,30,1,29,OPEN,2018-03-24,Saturday,21,Clouds,broken clouds,278.15,278.15,278.15,1007,80,2.1,290,75
823367,Custom House Quay,30,23,7,OPEN,2018-04-15,Sunday,19,Clouds,broken clouds,283.29,284.15,282.15,998,93,4.6,150,75
704060,Market Street South,38,38,0,OPEN,2018-04-12,Thursday,13,Drizzle,light intensity drizzle,280.15,280.15,280.15,1006,93,4.6,70,75

In [16]:
df_merge['Intercept'] = 1.0

In [17]:
limit = (df_merge.shape[0] * 7) // 10
limit

606026

In [18]:
df_train = df_merge[:limit]
df_test = df_merge[limit:]

In [19]:
X_train = df_train[descriptive]

y_train = df_train[target]

In [20]:
X_train = pd.get_dummies(X_train)

In [26]:
rfc = RandomForestClassifier(n_estimators=10, max_features='auto', oob_score=True, random_state=1)

In [27]:
rfc.fit(X_train, y_train)

/home/eoin/anaconda3/envs/Software/lib/python3.6/site-packages/sklearn/ensemble/forest.py:453: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
/home/eoin/anaconda3/envs/Software/lib/python3.6/site-packages/sklearn/ensemble/forest.py:458: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=True, random_state=1, verbose=0, warm_start=False)

In [28]:
predictions_train = rfc.predict(X_train)
print("Explained Variance:", metrics.explained_variance_score(y_train, predictions_train))
print("Mean Absolute Error:", metrics.mean_absolute_error(y_train, predictions_train))
print("R2 Score:", metrics.r2_score(y_train, predictions_train))

Explained Variance: 0.9467956873406768
Mean Absolute Error: 1.01441687320346
R2 Score: 0.946789507973502

In [29]:
def evaluator(X_train, X_test, y_train, y_test):
    rfc.fit(X_train, y_train)
    predictions = rfc.predict(X_test)
    print("Explained Variance:", metrics.explained_variance_score(y_test, predictions))
    print("Mean Absolute Error:", metrics.mean_absolute_error(y_test, predictions))
    print("R2 Score:", metrics.r2_score(y_test, predictions))

In [33]:
def tester(X_test, y_test):
    print("Explained Variance:", metrics.explained_variance_score(y_test, predictions))
    print("Mean Absolute Error:", metrics.mean_absolute_error(y_test, predictions))
    print("R2 Score:", metrics.r2_score(y_test, predictions))

In [31]:
X_test = df_test[descriptive]
y_test = df_test[target]
X_test = pd.get_dummies(X_test)

In [32]:
evaluator(X_train, X_test, y_train, y_test)

/home/eoin/anaconda3/envs/Software/lib/python3.6/site-packages/sklearn/ensemble/forest.py:453: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
/home/eoin/anaconda3/envs/Software/lib/python3.6/site-packages/sklearn/ensemble/forest.py:458: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])

Explained Variance: 0.9333198324089115
Mean Absolute Error: 1.3010634283822182
R2 Score: 0.9333179457181129

In [40]:
rfc = RandomForestClassifier(n_estimators=10, max_features='auto', oob_score=True, random_state=1)

In [41]:
X = df_merge[descriptive]
y = df_merge[target]
X = pd.get_dummies(X)
X = X.reindex_axis(sorted(X.columns), axis=1)
rfc.fit(X, y)

/home/eoin/anaconda3/envs/Software/lib/python3.6/site-packages/ipykernel/__main__.py:4: FutureWarning: '.reindex_axis' is deprecated and will be removed in a future version. Use '.reindex' instead.
/home/eoin/anaconda3/envs/Software/lib/python3.6/site-packages/sklearn/ensemble/forest.py:453: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
/home/eoin/anaconda3/envs/Software/lib/python3.6/site-packages/sklearn/ensemble/forest.py:458: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1, n_jobs=1,
            oob_score=True, random_state=1, verbose=0, warm_start=False)

In [38]:
pickle.dump(rfc, open( "model.p", "wb" ) )

In [42]:
from sklearn.externals import joblib
joblib.dump(rfc, 'model.pkl')

['model.pkl']